# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160921_2334'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articlePrivateUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='articlereg',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleprivateusers',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.articlereg'),
        ),
        migrations.AddField(
            model_name='articleprivateusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.UserDetail'),
        ),
    ]
