# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_banned_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereg',
            name='image',
            field=models.ImageField(default='article_images/<built-in function id>.jpg', upload_to=portal.models.content_file_name),
        ),
    ]
