# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20160909_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banned_user',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.UserDetail'),
        ),
    ]
