# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20160911_1213'),
        ('portal', '0007_auto_20160909_1418'),
    ]

    operations = [
    ]
