# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_merge_20160912_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='article_images/<built-in function id>.jpg', upload_to=portal.models.content_file_name)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlereg',
            name='image',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.articlereg'),
        ),
    ]
