# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20160912_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereg',
            name='status',
        ),
    ]
