# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='userID',
            new_name='userName',
        ),
    ]
