# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160921_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecovery',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
