# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160906_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visaNum', models.CharField(max_length=10)),
                ('expDate', models.DateTimeField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.UserDetail')),
            ],
        ),
    ]
