# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160923_0023'),
        ('signup', '0003_passwordrecovery_userid'),
    ]

    operations = [
    ]
