# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_visadetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisaDetails',
            new_name='Visa',
        ),
    ]
