# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_merge_20160923_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='interests',
            field=models.CharField(default='Vehicle', max_length=40, null=True),
        ),
    ]
